### ISSUE TITLE
Possibility to reset cached timeperiod parameters

### ISSUE THREAD

**Issue by xmatthias** [mrjbq7/ta-lib#306]
I'm currently investigating a  odd case, where the timeperiod seems to be cached somehow within ta-lib.

When using the following code - i would expect the columns `minusdi`, `minusdi2` and `minusdi_14` to be identical (default timeperiod for minusdi is 14). 
`minusdi_25` however should have a startup period of 25 (since it's the only one derriving from the default timeperiod of 14.

However, `minusdi2` is using timeperiod=25 instead of 14.

I've not seen this behaviour documented anywhere in the documentation (maybe a oversight or wording i didnt expect?).

Now this is creating a problem for us, since the same call to `MINUS_DI` can be in spread across multiple files, and whichever function is called first with parameter changes the default for all other calls.

Is there a way to reset this cached value - so i get the default "back" ? 

```
import talib.abstract as ta
import pandas as pd
import numpy as np


inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}
dataframe = pd.DataFrame(inputs)

dataframe['minusdi'] = ta.MINUS_DI(dataframe)
dataframe['minusdi_25'] = ta.MINUS_DI(dataframe, timeperiod=25)
dataframe['minusdi2'] = ta.MINUS_DI(dataframe)
dataframe['minusdi_14'] = ta.MINUS_DI(dataframe, timeperiod=14)
dataframe.head(25)
```

![2020-04-03-204420_757x671_scrot](https://user-images.githubusercontent.com/5024695/78394406-e6502d80-75eb-11ea-88ad-1187c562e0b9.png)

**Comment by briancappello** [comment]
@xmatthias This is fixed on `@master` (or rather, it will be if https://github.com/mrjbq7/ta-lib/pull/307 can be merged) but it doesn't look like there's been a release containing the necessary commits just yet

**Comment by mrjbq7** [comment]
I should probably do a new release.  I had been waiting to hear back from the user who requested TA_SetCompatibility changes.  I merged #307, so maybe @xmatthias can report if that fixes this issue.

If so, I'll probably just make a new release, it's been awhile.

**Comment by mrjbq7** [comment]
Thanks @briancappello !

**Comment by xmatthias** [comment]
I have to admit, i don't really understand HOW #307 fixes this issue (the pr seems to refer to dataframe - not the input period ...) - but using the latest master branch does indeed fix this, so a new release would be highly apreciated ...

**Comment by briancappello** [comment]
The specific issue you reported is indeed a bug/limitation present in `v0.4.17`, that just happened to have already been fixed in master. But when I was testing the sample code you posted, I realized there was also a bug on master when calling the abstract functions multiple times using a DataFrame as the input. So that's what #307 fixed.

**Comment by xmatthias** [comment]
Ah alright -  now the PR makes more sense :+1:

**Comment by xmatthias** [comment]
Unfortunately, also using the latest master does not seem to fix the issue completely.

Using the below code, i would expect `ema_default` and `ema_default2` / `ema_close` to align - but "price" seems  to be cached within ta-lib again ... causing the result to be unreliable, and heavily depend on the previous call.

```
import talib.abstract as ta
import pandas as pd

inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}
dataframe = pd.DataFrame(inputs)
dataframe['ema_default'] = ta.EMA(dataframe, timeperiod=5)
dataframe['ema_close'] = ta.EMA(dataframe, timeperiod=5, price='close')
dataframe['ema_low'] = ta.EMA(dataframe, timeperiod=5, price='low')
dataframe['ema_default2'] = ta.EMA(dataframe, timeperiod=5)
dataframe.head(20)
```

![2020-04-07-191557_770x558_scrot](https://user-images.githubusercontent.com/5024695/78699466-3db00f80-7904-11ea-83bc-1e2fa933202f.png)

**Comment by briancappello** [comment]
hmm yes, I can try to fix after work

**Comment by mrjbq7** [comment]
Try again, I merge #309.  Thanks @briancappello!

**Comment by xmatthias** [comment]
And once again - this seems to fix it! Thanks a lot!

**Comment by mrjbq7** [comment]
This has been fixed, and today released as 0.4.18.
